### ISSUE TITLE
Ayuda porfavor

### ISSUE THREAD

**Issue by Hyduez** [ElVideoFanXd10/Slash-Guide#1]
VideoFan me dijo q mi mama es fea y yo le conte todo a mi santisima madre y me dijo que no le haga caso ya que el es mas feo y yo llore

**Comment by ElVideoFanXd10** [comment]
> VideoFan me dijo q mi mama es fea y yo le conte todo a mi santisima madre y me dijo que no le haga caso ya que el es mas feo y yo llore

WTF

**Comment by ElVideoFanXd10** [comment]
quien lea esto es puto

**Comment by Mataisplays** [comment]
> quien lea esto es puto

![image](https://user-images.githubusercontent.com/88283458/133907303-e7ed3e0f-26b7-467b-abdc-832a5a0655d9.png)
